### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Lucretia** [vn7n24fzkq/github-profile-summary-cards#38]
**Describe the bug**

from https://github.com/anuraghazra/github-readme-stats/issues/270#issuecomment-806637761

> Hi @Lucretia .
> I was not sure would @anuraghazra fix this, so I made a repo that provide similar feature after my PR #307 was ignored.
> I hope this helps.
> https://github.com/vn7n24fzkq/github-profile-summary-cards

I tried to follow your instructions, but they're not correct. I had to add the yml file in the workflows directory myself, your instructions insinuate it would be added automatically.  Iit fails on the run action with:

```
Run vn7n24fzkq/github-profile-summary-cards@release
  with:
    USERNAME: Lucretia
  env:
    GITHUB_TOKEN: 
Start...
Remove old cards...
Creating ProfileDetailsCard...
Error: Error when creating ProfileDetailsCard 
Error: Request failed with status code 401
    at createError (/home/runner/work/_actions/vn7n24fzkq/github-profile-summary-cards/release/dist/index.js:9143:15)
    at settle (/home/runner/work/_actions/vn7n24fzkq/github-profile-summary-cards/release/dist/index.js:9402:12)
    at IncomingMessage.handleStreamEnd (/home/runner/work/_actions/vn7n24fzkq/github-profile-summary-cards/release/dist/index.js:8529:11)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1184:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Creating ReposPerLanguageCard...
Error: Error when creating ReposPerLanguageCard 
Error: Request failed with status code 401
    at createError (/home/runner/work/_actions/vn7n24fzkq/github-profile-summary-cards/release/dist/index.js:9143:15)
    at settle (/home/runner/work/_actions/vn7n24fzkq/github-profile-summary-cards/release/dist/index.js:9402:12)
    at IncomingMessage.handleStreamEnd (/home/runner/work/_actions/vn7n24fzkq/github-profile-summary-cards/release/dist/index.js:8529:11)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1184:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Creating CommitsPerLanguageCard...
Error: Error when creating CommitsPerLanguageCard 
Error: Request failed with status code 401
    at createError (/home/runner/work/_actions/vn7n24fzkq/github-profile-summary-cards/release/dist/index.js:9143:15)
    at settle (/home/runner/work/_actions/vn7n24fzkq/github-profile-summary-cards/release/dist/index.js:9402:12)
    at IncomingMessage.handleStreamEnd (/home/runner/work/_actions/vn7n24fzkq/github-profile-summary-cards/release/dist/index.js:8529:11)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1184:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Creating StatsCard...
Error: Error when creating StatsCard 
Error: Request failed with status code 401
    at createError (/home/runner/work/_actions/vn7n24fzkq/github-profile-summary-cards/release/dist/index.js:9143:15)
    at settle (/home/runner/work/_actions/vn7n24fzkq/github-profile-summary-cards/release/dist/index.js:9402:12)
    at IncomingMessage.handleStreamEnd (/home/runner/work/_actions/vn7n24fzkq/github-profile-summary-cards/release/dist/index.js:8529:11)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1184:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Creating ProductiveTimeCard...
Error: Error when creating ProductiveTimeCard 
Error: Request failed with status code 401
    at createError (/home/runner/work/_actions/vn7n24fzkq/github-profile-summary-cards/release/dist/index.js:9143:15)
    at settle (/home/runner/work/_actions/vn7n24fzkq/github-profile-summary-cards/release/dist/index.js:9402:12)
    at IncomingMessage.handleStreamEnd (/home/runner/work/_actions/vn7n24fzkq/github-profile-summary-cards/release/dist/index.js:8529:11)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1184:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Creating preview markdown...
Error: Error when creating preview markdown 
Error: ENOENT: no such file or directory, scandir './profile-summary-card-output/default'
    at Object.readdirSync (fs.js:854:3)
    at getAllFileInFolder (/home/runner/work/_actions/vn7n24fzkq/github-profile-summary-cards/release/dist/index.js:195990:6)
    at generateThemePreviewReadme (/home/runner/work/_actions/vn7n24fzkq/github-profile-summary-cards/release/dist/index.js:196044:20)
    at generatePreviewMarkdown (/home/runner/work/_actions/vn7n24fzkq/github-profile-summary-cards/release/dist/index.js:196006:5)
    at main (/home/runner/work/_actions/vn7n24fzkq/github-profile-summary-cards/release/dist/index.js:194588:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Commit file...
Warning: Commit failed. Retry...
Warning: Commit failed. Retry...
Error: Error: git add,./profile-summary-card-output/ 
  
 Invalid status code: 128
Error: git add,./profile-summary-card-output/ 
  
 Invalid status code: 128
```

I don't know if ```GITHUB_TOKEN: ``` should have my token pasted in there or if it's omitted on purpose.

**To Reproduce**
1. Follow the instructions from https://github.com/vn7n24fzkq/github-profile-summary-cards

**Expected behavior**
Expect to happen what's in the docs

**Screenshots**

**Desktop (please complete the following information):**
 - Linux
 - FF
 - 87.0

**Comment by vn7n24fzkq** [comment]
@Lucretia  Hi, thanks for your report.
Did you add a `Personal Access Token` to your repo as  a `SECRET`, and  required [permissions](https://github.com/vn7n24fzkq/github-profile-summary-cards/wiki/Personal-access-token-permissions) for token have been enabled.
`GITHUB_TOKEN: ` should be the name of `SECRET`.

Here is a  [Tutorial](https://github.com/vn7n24fzkq/github-profile-summary-cards/wiki/Toturial).

And I am planning to make a URL usage(#35) feature in the next week.

**Comment by Lucretia** [comment]
Yes, I did:

![pat](https://user-images.githubusercontent.com/570928/112654289-25077500-8e47-11eb-99cc-986e310a6add.png)
![secret](https://user-images.githubusercontent.com/570928/112654301-2769cf00-8e47-11eb-8eb3-86cd9ebd3bb4.png)
![yml](https://user-images.githubusercontent.com/570928/112654305-29339280-8e47-11eb-9e09-655c6497b2bd.png)

**Comment by vn7n24fzkq** [comment]
`GITHUB_TOKEN` should use `secrets` as a prefix. :thinking: 
It will looks like this.
`GITHUB_TOKEN: ${{ secrets.README }}`

**Comment by Lucretia** [comment]
Thanks that worked.
