### ISSUE TITLE
[BUG] Regenerated token no longer works

### ISSUE THREAD

**Issue by Lucretia** [vn7n24fzkq/github-profile-summary-cards#51]
GH complained that my token was out of date, so I regenerated it. Now the task will no longer run.

```
Error when creating ProfileDetailsCard 
Error: Request failed with status code 401
    at createError (/home/runner/work/_actions/vn7n24fzkq/github-profile-summary-cards/release/dist/index.js:9143:15)
    at settle (/home/runner/work/_actions/vn7n24fzkq/github-profile-summary-cards/release/dist/index.js:9402:12)
    at IncomingMessage.handleStreamEnd (/home/runner/work/_actions/vn7n24fzkq/github-profile-summary-cards/release/dist/index.js:8529:11)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1184:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

I get the above numerous times and then 2 commit failures.

**Comment by vn7n24fzkq** [comment]
Thanks for report.
Did you also update the repository secrets?
And make sure the token contains correct permission.

**Comment by Lucretia** [comment]
Thanks, that was it.
